fix whatever
trendscenter/coinstac-regression-vbm pull request #48
Opened 2022-10-31 20:18 UTC by rssk

2022-11-06 04:48 UTC, hvgazula commented on scripts/nipype_utils.py
> +        try:
@rssk Please remove this try except. You probably added it for debugging. Keep the line inside `try` and remove everything else.

2022-11-06 04:53 UTC, hvgazula requested changes
Please remove the `try-except` in nipype_utils.py (of course except for the line inside `try` block) and the rest looks good to me.

2022-11-06 16:15 UTC, hvgazula approved these changes

2022-11-17 21:13 UTC, rssk commented
> Please remove the `try-except` in nipype_utils.py (of course except for the line inside `try` block) and the rest looks good to me.

The reason for that was some extra debugging coinstac side, there is a condition where the files are present by python is saying it cant find them (ENOENT). So I'm trying to see what python is running into if that happens

2022-11-20 20:15 UTC, merged